### ISSUE TITLE
SVProgressHUD is outdated

### ISSUE THREAD

**Issue by dreampowder** [saltedge/saltedge-ios#62]
Hello there, please upgrade the podfile to use SVProgressHUD to 1.1.3 and change revelant codes in order to sample app work in ios 9+

**Comment by nemesis** [comment]
Thanks @dreampowder!

Side note: The app worked perfectly fine in iOS 9+, the only thing was that the `SVProgressHUD` had dark text on a dark background because of the little `sharedView` hacks that were removed in #63.
