### ISSUE TITLE
country_code vs allowed_countries

### ISSUE THREAD

**Issue by idanci** [saltedge/saltedge-ios#74]
Recently SE removed `country_code` option support and introduced `allowed_countries`.
Update SDK considering changes.

**Comment by idanci** [comment]
Initial report:

>> I’d like to let you know that we have made some changes to the API and added the possibility to filter the countries available to the customer through Salt Edge Connect.
>>
> > For more information, please check the “allowed_countries” parameter upon token creation. With Salt Edge Connect we strongly suggest using this parameter instead of “country_code”.
>>
>> Should you have any further questions, feel free to reach out to our support team.

> I checked the code and I noticed that the SE SDK will assert false if we don't send the country_code parameter.
```
NSAssert(parameters[kCountryCodeKey] != nil, @"Country code cannot be nil.");
```

**Comment by nemesis** [comment]
[3.1.3](https://cocoapods.org/pods/SaltEdge-iOS) removed presence validation for `country_code`, `provider_code`, and `return_to`.
