### ISSUE TITLE
SEAPIRequestManager method fetchFullProvidersListWithSuccess blocks main thread

### ISSUE THREAD

**Issue by LetsSee** [saltedge/saltedge-ios#87]
HI!

**All methods which use sendRequest:(SERequestMethod)method blocks UI!**

There are two possible fixes:
1. Just remove dispatch_async(dispatch_get_main_queue() call and give back responsibility to the user.
2. Remove  dispatch_async(dispatch_get_main_queue() call in sendRequest:(SERequestMethod)method and add those calls for success and failure blocks at the top level of the hierarchy.

SEAPIRequestManager method
-(void)fetchFullProvidersListWithSuccess:(void (^)(NSSet* providers))success
            failure: (SEAPIRequestFailureBlock)failure  - _SEAPIRequestManager.h (172)_
**block UI (main thread)** because of SERequestHandler method
- (void)sendRequest:(SERequestMethod)method
            withURL:(NSString*)url
            parameters:(NSDictionary*)parameters
            headers:(NSDictionary*)headers
            success:(SERequestHandlerSuccessBlock)success
            failure:(SERequestHandlerFailureBlock)failure

which dispatches entire completionHandler of NSURLSessionDataTask in main thread:
NSURLSessionDataTask* task = [_requestHandlerURLSession dataTaskWithRequest:request 
                                                       completionHandler:^(NSData* responseData, NSURLResponse* 
                                                        response, NSError* responseError) {
dispatch_async(dispatch_get_main_queue(), ^{
.....
_- SERequestHandler.m (119)_

Thanks

**Comment by nemesis** [comment]
Hey @LetsSee,

If you run the Time Profiler against the demo and dig through the traces, you'll notice that it's not the `SERequestHandler.sendRequest` that occupies the main thread when fetching the provider list, it's serializing the JSON objects from the response into their respective counterpart (in this case, `SEProvider`).

As soon as I find a workaround to this, I'll post an update and reference to this issue.

Thanks for getting in touch.

**Comment by nemesis** [comment]
@LetsSee, version [3.2.4](https://github.com/saltedge/saltedge-ios/releases/tag/v3.2.4) was released and is available on CocoaPods.

Please let us know if you encounter any issues.

**Comment by LetsSee** [comment]
@nemesis , thanks! That's exactly what i meant:)
